### ISSUE TITLE
When RUN MakeBas (https://zxplay.org/?m=128) the emulator reverts to 48k

### ISSUE THREAD

**Issue by gmarquis** [stever/zxplay#6]
Starting as https://zxplay.org/?m=128    Or,
https://zxplay.org/?m=128/projects/5b0f0dc2-a552-4322-9a25-2585da91e48a

When RUN code, emulator reverts to 48K

**Comment by stever** [comment]
Caching issue, I think. Let me know if the issue persists. Cloudflare used, which caches. I've tried purging the cache there. If you create a new project that should work as expected.

**Comment by gmarquis** [comment]
I just tried since you cleared Cloudflare ... no luck, starting url as 128k
with 128k active window, but RUN switches to 48k output .
Just so you know. Thanks.

**Comment by stever** [comment]
OK. I'll look into it. The machine itself is still 128K, as you can see
when you click the Reset button. However, the program could well be
loading in 48K mode...

**Comment by gmarquis** [comment]
Yes 'reset' will but this is, Makebas RUN with an active 128k screen in the
browser reverts 48k as the makebas output.

**Comment by stever** [comment]
Does the same with bas2tap used instead of zmakebas.

If autoLoadTapes is off, the Tape Loader can be used and it works in 128K basic.

I've reverted the default back to 48K, and providing a workaround that you can use: https://zxplay.org/?m=128&a=0
This uses 128K with autoLoadTapes off.

I suspect there's a conflict with how the `tape_128.szx` tape loader works.

**Comment by gmarquis** [comment]
So now, with https://zxplay.org/?m=128&a=0/projects/
Makebas RUN...The emulation remains 128k but no makebas code seems to be
used, maybe a frozen state after RUN.

**Comment by stever** [comment]
That URL should be https://zxplay.org/projects/?m=128&a=0 (the query string args go at the end). When you click the Run button you will see the machine boots into the usual startup, but you need to press Enter on the Tape Loader item to start the tape (which is ready otherwise).

**Comment by gmarquis** [comment]
Indeed, by Assembly I am used to reboot into the expected state via a
compiled .tap   .
Following MakeBas RUN now seems to be 128 mode in a frozen state. The test
code is just 10 PRINT or 10 REM
Maybe only the first time, but intermittently the big Play button is
presented resulting in a frozen state 128 window.


Glen.

**Comment by gmarquis** [comment]
Fresh Chrome window seems okay !!

**Comment by stever** [comment]
I was going to say it works for me so issue I don't reproduce here. Ah, maybe it was a caching issue this time! I figured it wasn't a caching issue earlier, after all. Maybe this time.
